/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Sep 13 2021
 * Processor: PIC16F877
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include<pic16f877.h>
#include "ADC.h"


 /************************
 Codigo de Prueba
 ***************************/
int main()
{
   int adcValue=0;
    
   TRISB = 0x00; 				//Configuro todo el puerto B como Output
   TRISD &= ~((1<<7) | (1<<6));	//Pongo como Output los pines RD6 y RD7 (hago un AND con 0b00111111)
   
   //TRISA=0b00001;
   TRISA |= (1<<0);				//EVARISTO WHY?
   
   ADC_Init();             			//Initialize the ADC module
   
   //Vamos a usar LATCHS. El puerto
   //RD6 y RD7 corresponden al Enable de cada LATCH.
   //Cuando uno esta en 0, el otro estara en 1.
   //Por lo tanto, se debe cumplir que RD6 = ~RD7
   

    while(1)
    {
       
        adcValue = ADC_Read(0);       // Read the ADC value of channel zero
       //Leo el valor del ADC, son 10 bytes (8 de la parte baja y 2 de la parte alta)
       
        adcValue = adcValue * 4.88; //EVARISTO WHY?
        
       //Pongo LE=1 al LATCH-1 y pongo LE=0 para el LATCH-2 y le envio la parte BAJA del ADC
        PORTD |= (1<<6);
        PORTD &= ~(1<<7);
        PORTB = (adcValue & 0xff);    		//Envio la parte BAJA (8 bits) al PORTB
        delay(1000);  						/** Wait */
       
	 //Pongo LE=1 al LATCH-2 y pongo LE=0 para el LATCH-1 y le envio la parte BAJA del ADC
        PORTD |= (1<<7);
        PORTD &= ~(1<<6);
        PORTB = (adcValue>>8) & 0x03; 		///Envio la parte ALTA (2 bits) al PORTB
        delay(1000);  						/** Wait */
    }
}